//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
namespace Shopbridge2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShopBridge
    {
        [Required]
        public int Item_Id { get; set; }
        [Required(ErrorMessage = "Please Enter Item name.")]
        [MaxLength(50)]
        [MinLength(3)]

        public string Item_Name { get; set; }
        [Required(ErrorMessage ="Please Enter Item type.")]
        [Display(Name ="Description")]
        [MinLength(3)]
        public string Item_type { get; set; }
        [Required(ErrorMessage = "Please Enter Item Price.")]
        [Range(5,5000)]
        public Nullable<int> Price { get; set; }
        [Required(ErrorMessage = "Please Enter Item quantity.")]
        [Range(1,10000)]
        public Nullable<int> Quantity { get; set; }
    }
}
